2025-08-29 15:46:11.787 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration bssci_mioty which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-08-29 15:46:11.849 INFO (MainThread) [homeassistant.setup] Setup of domain logger took 0.0 seconds
2025-08-29 15:46:11.854 INFO (MainThread) [homeassistant.bootstrap] Setting up frontend: {'frontend'}
2025-08-29 15:46:11.857 INFO (MainThread) [homeassistant.setup] Setting up device_automation
2025-08-29 15:46:11.857 INFO (MainThread) [homeassistant.setup] Setup of domain device_automation took 0.0 seconds
2025-08-29 15:46:11.858 INFO (MainThread) [homeassistant.setup] Setting up http
2025-08-29 15:46:11.858 INFO (MainThread) [homeassistant.setup] Setting up lovelace
2025-08-29 15:46:11.860 INFO (MainThread) [homeassistant.setup] Setup of domain lovelace took 0.0 seconds
2025-08-29 15:46:11.864 INFO (MainThread) [homeassistant.setup] Setup of domain http took 0.0 seconds
2025-08-29 15:46:11.866 INFO (MainThread) [homeassistant.setup] Setting up repairs
2025-08-29 15:46:11.867 INFO (MainThread) [homeassistant.setup] Setup of domain repairs took 0.0 seconds
2025-08-29 15:46:11.867 INFO (MainThread) [homeassistant.setup] Setting up websocket_api
2025-08-29 15:46:11.867 INFO (MainThread) [homeassistant.setup] Setup of domain websocket_api took 0.0 seconds
2025-08-29 15:46:11.888 INFO (MainThread) [homeassistant.setup] Setting up image_upload
2025-08-29 15:46:11.889 INFO (MainThread) [homeassistant.setup] Setting up api
2025-08-29 15:46:11.891 INFO (MainThread) [homeassistant.setup] Setup of domain api took 0.0 seconds
2025-08-29 15:46:11.891 INFO (MainThread) [homeassistant.setup] Setting up auth
2025-08-29 15:46:11.892 INFO (MainThread) [homeassistant.setup] Setup of domain auth took 0.0 seconds
2025-08-29 15:46:11.892 INFO (MainThread) [homeassistant.setup] Setting up config
2025-08-29 15:46:11.925 INFO (MainThread) [homeassistant.setup] Setup of domain config took 0.0 seconds
2025-08-29 15:46:11.927 INFO (MainThread) [homeassistant.setup] Setting up diagnostics
2025-08-29 15:46:11.929 INFO (MainThread) [homeassistant.setup] Setup of domain diagnostics took 0.0 seconds
2025-08-29 15:46:11.933 INFO (MainThread) [homeassistant.setup] Setting up file_upload
2025-08-29 15:46:11.933 INFO (MainThread) [homeassistant.setup] Setup of domain file_upload took 0.0 seconds
2025-08-29 15:46:11.942 INFO (MainThread) [homeassistant.setup] Setting up search
2025-08-29 15:46:11.942 INFO (MainThread) [homeassistant.setup] Setup of domain search took 0.0 seconds
2025-08-29 15:46:11.943 INFO (MainThread) [homeassistant.setup] Setup of domain image_upload took 0.1 seconds
2025-08-29 15:46:11.944 INFO (MainThread) [homeassistant.setup] Setting up person
2025-08-29 15:46:11.944 INFO (SyncWorker_1) [homeassistant.loader] Loaded history from homeassistant.components.history
2025-08-29 15:46:11.945 INFO (MainThread) [homeassistant.setup] Setup of domain person took 0.0 seconds
2025-08-29 15:46:12.376 INFO (MainThread) [homeassistant.setup] Setting up analytics
2025-08-29 15:46:12.376 INFO (MainThread) [homeassistant.setup] Setup of domain analytics took 0.0 seconds
2025-08-29 15:46:12.377 INFO (MainThread) [homeassistant.setup] Setting up onboarding
2025-08-29 15:46:12.378 INFO (MainThread) [homeassistant.setup] Setup of domain onboarding took 0.0 seconds
2025-08-29 15:46:12.378 INFO (MainThread) [homeassistant.setup] Setting up frontend
2025-08-29 15:46:12.380 INFO (MainThread) [homeassistant.setup] Setup of domain frontend took 0.0 seconds
2025-08-29 15:46:12.381 INFO (MainThread) [homeassistant.bootstrap] Setting up recorder: {'recorder'}
2025-08-29 15:46:12.382 INFO (MainThread) [homeassistant.setup] Setting up recorder
2025-08-29 15:46:12.387 INFO (MainThread) [homeassistant.components.http] Now listening on port 5000
2025-08-29 15:46:12.396 WARNING (Recorder) [homeassistant.components.recorder.util] Ended unfinished session (id=1 from 2025-08-29 15:45:11.378870)
2025-08-29 15:46:12.414 INFO (MainThread) [homeassistant.setup] Setup of domain recorder took 0.0 seconds
2025-08-29 15:46:12.414 INFO (MainThread) [homeassistant.bootstrap] Setting up stage 2: {'backup', 'automation', 'zone', 'search', 'analytics', 'blueprint', 'repairs', 'network', 'input_select', 'input_button', 'input_datetime', 'diagnostics', 'trace', 'file_upload', 'schedule', 'auth', 'script', 'device_automation', 'onboarding', 'lovelace', 'person', 'api', 'http', 'scene', 'input_boolean', 'hardware', 'application_credentials', 'websocket_api', 'tag', 'image_upload', 'system_health', 'input_text', 'sun', 'timer', 'counter', 'config', 'input_number', 'sensor'}
2025-08-29 15:46:12.416 INFO (MainThread) [homeassistant.setup] Setting up zone
2025-08-29 15:46:12.416 INFO (MainThread) [homeassistant.setup] Setting up blueprint
2025-08-29 15:46:12.417 INFO (MainThread) [homeassistant.setup] Setup of domain blueprint took 0.0 seconds
2025-08-29 15:46:12.424 INFO (MainThread) [homeassistant.setup] Setting up input_select
2025-08-29 15:46:12.428 INFO (MainThread) [homeassistant.setup] Setting up input_datetime
2025-08-29 15:46:12.431 INFO (MainThread) [homeassistant.setup] Setting up network
2025-08-29 15:46:12.433 INFO (MainThread) [homeassistant.setup] Setup of domain network took 0.0 seconds
2025-08-29 15:46:12.437 INFO (MainThread) [homeassistant.setup] Setting up input_button
2025-08-29 15:46:12.438 INFO (MainThread) [homeassistant.setup] Setting up trace
2025-08-29 15:46:12.438 INFO (MainThread) [homeassistant.setup] Setup of domain trace took 0.0 seconds
2025-08-29 15:46:12.443 INFO (MainThread) [homeassistant.setup] Setting up schedule
2025-08-29 15:46:12.443 INFO (MainThread) [homeassistant.setup] Setting up scene
2025-08-29 15:46:12.444 INFO (MainThread) [homeassistant.components.scene] Setting up homeassistant.scene
2025-08-29 15:46:12.445 INFO (MainThread) [homeassistant.setup] Setting up input_boolean
2025-08-29 15:46:12.452 INFO (MainThread) [homeassistant.setup] Setting up application_credentials
2025-08-29 15:46:12.454 INFO (MainThread) [homeassistant.setup] Setting up tag
2025-08-29 15:46:12.455 INFO (MainThread) [homeassistant.setup] Setting up system_health
2025-08-29 15:46:12.457 INFO (MainThread) [homeassistant.setup] Setup of domain system_health took 0.0 seconds
2025-08-29 15:46:12.458 INFO (MainThread) [homeassistant.setup] Setting up input_text
2025-08-29 15:46:12.459 INFO (MainThread) [homeassistant.setup] Setting up sun
2025-08-29 15:46:12.459 INFO (MainThread) [homeassistant.setup] Setup of domain sun took 0.0 seconds
2025-08-29 15:46:12.460 INFO (MainThread) [homeassistant.setup] Setting up timer
2025-08-29 15:46:12.461 INFO (MainThread) [homeassistant.setup] Setting up counter
2025-08-29 15:46:12.463 INFO (MainThread) [homeassistant.setup] Setting up input_number
2025-08-29 15:46:12.463 INFO (SyncWorker_1) [homeassistant.loader] Loaded time_date from homeassistant.components.time_date
2025-08-29 15:46:12.465 INFO (MainThread) [homeassistant.setup] Setting up backup
2025-08-29 15:46:12.466 INFO (MainThread) [homeassistant.setup] Setup of domain backup took 0.0 seconds
2025-08-29 15:46:12.467 INFO (MainThread) [homeassistant.setup] Setting up hardware
2025-08-29 15:46:12.483 INFO (MainThread) [homeassistant.setup] Setting up sensor
2025-08-29 15:46:12.484 INFO (MainThread) [homeassistant.setup] Setup of domain sensor took 0.0 seconds
2025-08-29 15:46:12.484 INFO (MainThread) [homeassistant.setup] Setting up script
2025-08-29 15:46:12.484 INFO (MainThread) [homeassistant.setup] Setup of domain scene took 0.0 seconds
2025-08-29 15:46:12.486 INFO (MainThread) [homeassistant.setup] Setting up automation
2025-08-29 15:46:12.493 INFO (MainThread) [homeassistant.components.sensor] Setting up sun.sensor
2025-08-29 15:46:12.494 INFO (MainThread) [homeassistant.setup] Setup of domain zone took 0.1 seconds
2025-08-29 15:46:12.496 INFO (MainThread) [homeassistant.setup] Setup of domain input_select took 0.1 seconds
2025-08-29 15:46:12.497 INFO (MainThread) [homeassistant.setup] Setup of domain input_datetime took 0.1 seconds
2025-08-29 15:46:12.497 INFO (MainThread) [homeassistant.setup] Setup of domain input_button took 0.1 seconds
2025-08-29 15:46:12.498 INFO (MainThread) [homeassistant.setup] Setup of domain script took 0.0 seconds
2025-08-29 15:46:12.498 INFO (MainThread) [homeassistant.components.sensor] Setting up time_date.sensor
2025-08-29 15:46:12.500 INFO (MainThread) [homeassistant.setup] Setup of domain automation took 0.0 seconds
2025-08-29 15:46:12.500 INFO (MainThread) [homeassistant.setup] Setup of domain hardware took 0.0 seconds
2025-08-29 15:46:12.506 INFO (MainThread) [homeassistant.setup] Setup of domain schedule took 0.1 seconds
2025-08-29 15:46:12.507 INFO (MainThread) [homeassistant.setup] Setup of domain input_boolean took 0.1 seconds
2025-08-29 15:46:12.508 INFO (MainThread) [homeassistant.setup] Setup of domain application_credentials took 0.1 seconds
2025-08-29 15:46:12.509 INFO (MainThread) [homeassistant.setup] Setup of domain tag took 0.1 seconds
2025-08-29 15:46:12.511 INFO (MainThread) [homeassistant.setup] Setup of domain input_text took 0.1 seconds
2025-08-29 15:46:12.512 INFO (MainThread) [homeassistant.setup] Setup of domain counter took 0.1 seconds
2025-08-29 15:46:12.514 INFO (MainThread) [homeassistant.setup] Setup of domain timer took 0.1 seconds
2025-08-29 15:46:12.516 INFO (MainThread) [homeassistant.setup] Setup of domain input_number took 0.1 seconds
2025-08-29 15:46:12.517 INFO (MainThread) [homeassistant.bootstrap] Home Assistant initialized in 0.74s
2025-08-29 15:46:12.517 WARNING (MainThread) [homeassistant.bootstrap] Support for the running Python version 3.11.13 is deprecated and will be removed in Home Assistant 2024.4; Please upgrade Python to 3.12
2025-08-29 15:46:12.517 INFO (MainThread) [homeassistant.core] Starting Home Assistant
2025-08-29 15:46:30.898 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/homeassistant/components/http/security_filter.py", line 91, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/homeassistant/components/http/forwarded.py", line 82, in forwarded_middleware
    from hass_nabucasa import (  # pylint: disable=import-outside-toplevel
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/hass_nabucasa/__init__.py", line 29, in <module>
    from .remote import RemoteUI
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/hass_nabucasa/remote.py", line 21, in <module>
    from .acme import AcmeClientError, AcmeHandler
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/hass_nabucasa/acme.py", line 13, in <module>
    from acme import challenges, client, crypto_util, errors, messages
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/acme/challenges.py", line 24, in <module>
    from acme import crypto_util
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/acme/crypto_util.py", line 435, in <module>
    def dump_pyopenssl_chain(chain: Union[List[jose.ComparableX509], List[crypto.X509]],
                                               ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'josepy' has no attribute 'ComparableX509'
2025-08-29 15:47:40.767 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/homeassistant/components/http/security_filter.py", line 91, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/homeassistant/components/http/forwarded.py", line 82, in forwarded_middleware
    from hass_nabucasa import (  # pylint: disable=import-outside-toplevel
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/hass_nabucasa/__init__.py", line 29, in <module>
    from .remote import RemoteUI
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/hass_nabucasa/remote.py", line 21, in <module>
    from .acme import AcmeClientError, AcmeHandler
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/hass_nabucasa/acme.py", line 13, in <module>
    from acme import challenges, client, crypto_util, errors, messages
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/acme/challenges.py", line 24, in <module>
    from acme import crypto_util
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/acme/crypto_util.py", line 435, in <module>
    def dump_pyopenssl_chain(chain: Union[List[jose.ComparableX509], List[crypto.X509]],
                                               ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'josepy' has no attribute 'ComparableX509'
2025-08-29 15:47:40.917 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/homeassistant/components/http/security_filter.py", line 91, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/homeassistant/components/http/forwarded.py", line 82, in forwarded_middleware
    from hass_nabucasa import (  # pylint: disable=import-outside-toplevel
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/hass_nabucasa/__init__.py", line 29, in <module>
    from .remote import RemoteUI
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/hass_nabucasa/remote.py", line 21, in <module>
    from .acme import AcmeClientError, AcmeHandler
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/hass_nabucasa/acme.py", line 13, in <module>
    from acme import challenges, client, crypto_util, errors, messages
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/acme/challenges.py", line 24, in <module>
    from acme import crypto_util
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/acme/crypto_util.py", line 435, in <module>
    def dump_pyopenssl_chain(chain: Union[List[jose.ComparableX509], List[crypto.X509]],
                                               ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'josepy' has no attribute 'ComparableX509'
2025-08-29 15:47:41.400 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/homeassistant/components/http/security_filter.py", line 91, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/homeassistant/components/http/forwarded.py", line 82, in forwarded_middleware
    from hass_nabucasa import (  # pylint: disable=import-outside-toplevel
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/hass_nabucasa/__init__.py", line 29, in <module>
    from .remote import RemoteUI
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/hass_nabucasa/remote.py", line 21, in <module>
    from .acme import AcmeClientError, AcmeHandler
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/hass_nabucasa/acme.py", line 13, in <module>
    from acme import challenges, client, crypto_util, errors, messages
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/acme/challenges.py", line 24, in <module>
    from acme import crypto_util
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/acme/crypto_util.py", line 435, in <module>
    def dump_pyopenssl_chain(chain: Union[List[jose.ComparableX509], List[crypto.X509]],
                                               ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'josepy' has no attribute 'ComparableX509'
2025-08-29 15:47:41.487 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/homeassistant/components/http/security_filter.py", line 91, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/homeassistant/components/http/forwarded.py", line 82, in forwarded_middleware
    from hass_nabucasa import (  # pylint: disable=import-outside-toplevel
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/hass_nabucasa/__init__.py", line 29, in <module>
    from .remote import RemoteUI
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/hass_nabucasa/remote.py", line 21, in <module>
    from .acme import AcmeClientError, AcmeHandler
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/hass_nabucasa/acme.py", line 13, in <module>
    from acme import challenges, client, crypto_util, errors, messages
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/acme/challenges.py", line 24, in <module>
    from acme import crypto_util
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/acme/crypto_util.py", line 435, in <module>
    def dump_pyopenssl_chain(chain: Union[List[jose.ComparableX509], List[crypto.X509]],
                                               ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'josepy' has no attribute 'ComparableX509'
2025-08-29 15:48:17.262 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/homeassistant/components/http/security_filter.py", line 91, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/homeassistant/components/http/forwarded.py", line 82, in forwarded_middleware
    from hass_nabucasa import (  # pylint: disable=import-outside-toplevel
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/hass_nabucasa/__init__.py", line 29, in <module>
    from .remote import RemoteUI
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/hass_nabucasa/remote.py", line 21, in <module>
    from .acme import AcmeClientError, AcmeHandler
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/hass_nabucasa/acme.py", line 13, in <module>
    from acme import challenges, client, crypto_util, errors, messages
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/acme/challenges.py", line 24, in <module>
    from acme import crypto_util
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/acme/crypto_util.py", line 435, in <module>
    def dump_pyopenssl_chain(chain: Union[List[jose.ComparableX509], List[crypto.X509]],
                                               ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'josepy' has no attribute 'ComparableX509'
2025-08-29 15:48:17.417 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/homeassistant/components/http/security_filter.py", line 91, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/homeassistant/components/http/forwarded.py", line 82, in forwarded_middleware
    from hass_nabucasa import (  # pylint: disable=import-outside-toplevel
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/hass_nabucasa/__init__.py", line 29, in <module>
    from .remote import RemoteUI
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/hass_nabucasa/remote.py", line 21, in <module>
    from .acme import AcmeClientError, AcmeHandler
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/hass_nabucasa/acme.py", line 13, in <module>
    from acme import challenges, client, crypto_util, errors, messages
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/acme/challenges.py", line 24, in <module>
    from acme import crypto_util
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/acme/crypto_util.py", line 435, in <module>
    def dump_pyopenssl_chain(chain: Union[List[jose.ComparableX509], List[crypto.X509]],
                                               ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'josepy' has no attribute 'ComparableX509'
2025-08-29 15:48:17.667 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/homeassistant/components/http/security_filter.py", line 91, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/homeassistant/components/http/forwarded.py", line 82, in forwarded_middleware
    from hass_nabucasa import (  # pylint: disable=import-outside-toplevel
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/hass_nabucasa/__init__.py", line 29, in <module>
    from .remote import RemoteUI
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/hass_nabucasa/remote.py", line 21, in <module>
    from .acme import AcmeClientError, AcmeHandler
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/hass_nabucasa/acme.py", line 13, in <module>
    from acme import challenges, client, crypto_util, errors, messages
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/acme/challenges.py", line 24, in <module>
    from acme import crypto_util
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/acme/crypto_util.py", line 435, in <module>
    def dump_pyopenssl_chain(chain: Union[List[jose.ComparableX509], List[crypto.X509]],
                                               ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'josepy' has no attribute 'ComparableX509'
2025-08-29 15:48:17.672 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/homeassistant/components/http/security_filter.py", line 91, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/homeassistant/components/http/forwarded.py", line 82, in forwarded_middleware
    from hass_nabucasa import (  # pylint: disable=import-outside-toplevel
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/hass_nabucasa/__init__.py", line 29, in <module>
    from .remote import RemoteUI
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/hass_nabucasa/remote.py", line 21, in <module>
    from .acme import AcmeClientError, AcmeHandler
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/hass_nabucasa/acme.py", line 13, in <module>
    from acme import challenges, client, crypto_util, errors, messages
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/acme/challenges.py", line 24, in <module>
    from acme import crypto_util
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/acme/crypto_util.py", line 435, in <module>
    def dump_pyopenssl_chain(chain: Union[List[jose.ComparableX509], List[crypto.X509]],
                                               ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'josepy' has no attribute 'ComparableX509'
2025-08-29 16:01:06.568 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/homeassistant/components/http/security_filter.py", line 91, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/homeassistant/components/http/forwarded.py", line 82, in forwarded_middleware
    from hass_nabucasa import (  # pylint: disable=import-outside-toplevel
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/hass_nabucasa/__init__.py", line 29, in <module>
    from .remote import RemoteUI
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/hass_nabucasa/remote.py", line 21, in <module>
    from .acme import AcmeClientError, AcmeHandler
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/hass_nabucasa/acme.py", line 13, in <module>
    from acme import challenges, client, crypto_util, errors, messages
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/acme/challenges.py", line 24, in <module>
    from acme import crypto_util
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/acme/crypto_util.py", line 435, in <module>
    def dump_pyopenssl_chain(chain: Union[List[jose.ComparableX509], List[crypto.X509]],
                                               ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'josepy' has no attribute 'ComparableX509'
2025-08-29 16:01:07.674 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/homeassistant/components/http/security_filter.py", line 91, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/homeassistant/components/http/forwarded.py", line 82, in forwarded_middleware
    from hass_nabucasa import (  # pylint: disable=import-outside-toplevel
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/hass_nabucasa/__init__.py", line 29, in <module>
    from .remote import RemoteUI
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/hass_nabucasa/remote.py", line 21, in <module>
    from .acme import AcmeClientError, AcmeHandler
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/hass_nabucasa/acme.py", line 13, in <module>
    from acme import challenges, client, crypto_util, errors, messages
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/acme/challenges.py", line 24, in <module>
    from acme import crypto_util
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/acme/crypto_util.py", line 435, in <module>
    def dump_pyopenssl_chain(chain: Union[List[jose.ComparableX509], List[crypto.X509]],
                                               ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'josepy' has no attribute 'ComparableX509'
2025-08-29 16:01:10.492 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/homeassistant/components/http/security_filter.py", line 91, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/homeassistant/components/http/forwarded.py", line 82, in forwarded_middleware
    from hass_nabucasa import (  # pylint: disable=import-outside-toplevel
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/hass_nabucasa/__init__.py", line 29, in <module>
    from .remote import RemoteUI
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/hass_nabucasa/remote.py", line 21, in <module>
    from .acme import AcmeClientError, AcmeHandler
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/hass_nabucasa/acme.py", line 13, in <module>
    from acme import challenges, client, crypto_util, errors, messages
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/acme/challenges.py", line 24, in <module>
    from acme import crypto_util
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/acme/crypto_util.py", line 435, in <module>
    def dump_pyopenssl_chain(chain: Union[List[jose.ComparableX509], List[crypto.X509]],
                                               ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'josepy' has no attribute 'ComparableX509'
2025-08-29 16:01:10.650 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/homeassistant/components/http/security_filter.py", line 91, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/homeassistant/components/http/forwarded.py", line 82, in forwarded_middleware
    from hass_nabucasa import (  # pylint: disable=import-outside-toplevel
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/hass_nabucasa/__init__.py", line 29, in <module>
    from .remote import RemoteUI
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/hass_nabucasa/remote.py", line 21, in <module>
    from .acme import AcmeClientError, AcmeHandler
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/hass_nabucasa/acme.py", line 13, in <module>
    from acme import challenges, client, crypto_util, errors, messages
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/acme/challenges.py", line 24, in <module>
    from acme import crypto_util
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/acme/crypto_util.py", line 435, in <module>
    def dump_pyopenssl_chain(chain: Union[List[jose.ComparableX509], List[crypto.X509]],
                                               ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'josepy' has no attribute 'ComparableX509'
2025-08-29 16:01:10.971 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/homeassistant/components/http/security_filter.py", line 91, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/homeassistant/components/http/forwarded.py", line 82, in forwarded_middleware
    from hass_nabucasa import (  # pylint: disable=import-outside-toplevel
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/hass_nabucasa/__init__.py", line 29, in <module>
    from .remote import RemoteUI
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/hass_nabucasa/remote.py", line 21, in <module>
    from .acme import AcmeClientError, AcmeHandler
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/hass_nabucasa/acme.py", line 13, in <module>
    from acme import challenges, client, crypto_util, errors, messages
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/acme/challenges.py", line 24, in <module>
    from acme import crypto_util
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/acme/crypto_util.py", line 435, in <module>
    def dump_pyopenssl_chain(chain: Union[List[jose.ComparableX509], List[crypto.X509]],
                                               ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'josepy' has no attribute 'ComparableX509'
2025-08-29 16:01:11.090 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/homeassistant/components/http/security_filter.py", line 91, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/homeassistant/components/http/forwarded.py", line 82, in forwarded_middleware
    from hass_nabucasa import (  # pylint: disable=import-outside-toplevel
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/hass_nabucasa/__init__.py", line 29, in <module>
    from .remote import RemoteUI
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/hass_nabucasa/remote.py", line 21, in <module>
    from .acme import AcmeClientError, AcmeHandler
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/hass_nabucasa/acme.py", line 13, in <module>
    from acme import challenges, client, crypto_util, errors, messages
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/acme/challenges.py", line 24, in <module>
    from acme import crypto_util
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/acme/crypto_util.py", line 435, in <module>
    def dump_pyopenssl_chain(chain: Union[List[jose.ComparableX509], List[crypto.X509]],
                                               ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'josepy' has no attribute 'ComparableX509'
2025-08-29 16:03:30.790 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/homeassistant/components/http/security_filter.py", line 91, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/homeassistant/components/http/forwarded.py", line 82, in forwarded_middleware
    from hass_nabucasa import (  # pylint: disable=import-outside-toplevel
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/hass_nabucasa/__init__.py", line 29, in <module>
    from .remote import RemoteUI
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/hass_nabucasa/remote.py", line 21, in <module>
    from .acme import AcmeClientError, AcmeHandler
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/hass_nabucasa/acme.py", line 13, in <module>
    from acme import challenges, client, crypto_util, errors, messages
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/acme/challenges.py", line 24, in <module>
    from acme import crypto_util
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/acme/crypto_util.py", line 435, in <module>
    def dump_pyopenssl_chain(chain: Union[List[jose.ComparableX509], List[crypto.X509]],
                                               ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'josepy' has no attribute 'ComparableX509'
2025-08-29 16:03:30.974 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/homeassistant/components/http/security_filter.py", line 91, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/homeassistant/components/http/forwarded.py", line 82, in forwarded_middleware
    from hass_nabucasa import (  # pylint: disable=import-outside-toplevel
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/hass_nabucasa/__init__.py", line 29, in <module>
    from .remote import RemoteUI
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/hass_nabucasa/remote.py", line 21, in <module>
    from .acme import AcmeClientError, AcmeHandler
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/hass_nabucasa/acme.py", line 13, in <module>
    from acme import challenges, client, crypto_util, errors, messages
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/acme/challenges.py", line 24, in <module>
    from acme import crypto_util
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/acme/crypto_util.py", line 435, in <module>
    def dump_pyopenssl_chain(chain: Union[List[jose.ComparableX509], List[crypto.X509]],
                                               ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'josepy' has no attribute 'ComparableX509'
2025-08-29 16:03:31.459 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/homeassistant/components/http/security_filter.py", line 91, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/homeassistant/components/http/forwarded.py", line 82, in forwarded_middleware
    from hass_nabucasa import (  # pylint: disable=import-outside-toplevel
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/hass_nabucasa/__init__.py", line 29, in <module>
    from .remote import RemoteUI
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/hass_nabucasa/remote.py", line 21, in <module>
    from .acme import AcmeClientError, AcmeHandler
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/hass_nabucasa/acme.py", line 13, in <module>
    from acme import challenges, client, crypto_util, errors, messages
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/acme/challenges.py", line 24, in <module>
    from acme import crypto_util
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/acme/crypto_util.py", line 435, in <module>
    def dump_pyopenssl_chain(chain: Union[List[jose.ComparableX509], List[crypto.X509]],
                                               ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'josepy' has no attribute 'ComparableX509'
2025-08-29 16:03:31.631 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/homeassistant/components/http/security_filter.py", line 91, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/homeassistant/components/http/forwarded.py", line 82, in forwarded_middleware
    from hass_nabucasa import (  # pylint: disable=import-outside-toplevel
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/hass_nabucasa/__init__.py", line 29, in <module>
    from .remote import RemoteUI
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/hass_nabucasa/remote.py", line 21, in <module>
    from .acme import AcmeClientError, AcmeHandler
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/hass_nabucasa/acme.py", line 13, in <module>
    from acme import challenges, client, crypto_util, errors, messages
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/acme/challenges.py", line 24, in <module>
    from acme import crypto_util
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/acme/crypto_util.py", line 435, in <module>
    def dump_pyopenssl_chain(chain: Union[List[jose.ComparableX509], List[crypto.X509]],
                                               ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'josepy' has no attribute 'ComparableX509'
2025-08-29 16:10:59.601 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/homeassistant/components/http/security_filter.py", line 91, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/homeassistant/components/http/forwarded.py", line 82, in forwarded_middleware
    from hass_nabucasa import (  # pylint: disable=import-outside-toplevel
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/hass_nabucasa/__init__.py", line 29, in <module>
    from .remote import RemoteUI
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/hass_nabucasa/remote.py", line 21, in <module>
    from .acme import AcmeClientError, AcmeHandler
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/hass_nabucasa/acme.py", line 13, in <module>
    from acme import challenges, client, crypto_util, errors, messages
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/acme/challenges.py", line 24, in <module>
    from acme import crypto_util
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/acme/crypto_util.py", line 435, in <module>
    def dump_pyopenssl_chain(chain: Union[List[jose.ComparableX509], List[crypto.X509]],
                                               ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'josepy' has no attribute 'ComparableX509'
2025-08-29 16:52:59.164 INFO (Recorder) [homeassistant.components.recorder.pool.RecorderPool] Pool recreating
